<?php
session_start();
include('config.php');
if(!$_SESSION['pseudo']) {
    header('Location: connexion.php');
}
?>


<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css" href="../styles/A_PROPOS_DE_LARTISTE.css">
</head>
<body>
<h1>CHANTER ET M'EXPRIMER</h1>
<h3>
J'AI 28 ANS, JE SUIS ORIGINAIRE DU RHÔNE ALPES MAIS J'AI GRANDI<br />
PRINCIPALEMENT EN HAUTE NORMANDIE ET DEPUIS JE RÉSIDE QUELQUE PART<br />
AU MILIEU DE CETTE NORMANDIE!<br>
PERSONNE NE FAISAIT DES MUSIQUES CHEZ MOI MAIS FAIS DES<br />
RENCONTRES STIMULANTES DANS MON QUARTIER IL Y A LONGTEMPS (2006)<br />
CE QUI M'A CONDUIT VERS CETTE PASSION. J'AI CRÉÉ ALORS DES<br />
ASSOCIATIONS ET JE ME SUIS MIS EN LIEN AVEC CERTAINES MUNICIPALITÉS<br />
DANS LE BUT DE DÉPASSER MON HANDICAP : LA MUSIQUE COMME THÉRAPIE<br />
COMME COMBAT, COMME EXPRESSION, COMME IMAGINATION, <br />
COMME LIEN SOCIAL.<br />
ÉCRIRE SUR MA RÉALITÉ ET MON RESSENTIS DEPUIS LE DÉBUT ME MOTIVE.<br />
JE ME SUIS TOURNÉ NATURELLEMENT VERS LE RAP TRÈS PRÉSENT DANS MON <br />
ENVIRONNEMENT. J'AI PU Y INTRODUIRE MON IMPATIENCE FACE AU MONDE ET <br />
AUX GENS. MAIS DEPUIS J'AI RÉUSSI À ME DÉCENTRER DE MOI-MÊME <br />
POUR ESSAYER DE ME METTRE À LA PLACE DES GENS ET À L'ÉCOUTE DU<br /> 
MONDE QUI M'ENTOURE. DANS UN SOUCIS DE PRODUIRE DES OEUVRES<br />
ORIGINALES AVEC DES MOYENS PROFESSIONNELS JE SUIS ENTRÉ EN STUDIO<br />
D'ENREGISTREMENT DE PLUS EN PLUS SOUVENT. JE SITU MON TRAVAIL ENTRE<br />
RAP RNB ET SLAM. DÉSORMAIS MES ZONES D'INSPIRATION SE CROISENT<br />
AUTOUR DE THÈMES COMME LES SENTIMENTS DE LA COLÈRE,DE L'ANGOISSE<br />
ET DE L'AMOUR.
</h3>
<footer>
<nav class="navbar navbar">
<div class="container"><br>
<p class="Para" id="Le_Para">POSITIVE HANDICAP</p>
<p class="Para2" id="Le_Para2">DÉPASSER LE HANDICAP : LA MUSIQUE COMME THÉRAPIE,COMME COMBAT,<br />
COMME EXPRESSION,COMME IMAGINATION, COMME LIEN SOCIAL !</p><br /> <br />
<p class="Mini_Para" id="Le_Mini_Para">TOUTES LES OEUVRES PRÉSENTÉS SUR LE SITE SONT LA PROPRIÉTÉ DE M.TRISTAN BEARD.<br />
TOUTE L'UTILISATION DEVRA FAIRE L'OBJET D4UNE DEMANDE D'AUTORISATION VIA LE FORMULAIRE DE CONTACT.<br />
TOUTE UTILISATION ILLICITE POURRAIT FAIRE L4OBJET DE POURSUITES.</p>
<img src="../Image/titan-fm-logo copie 1.png" id="Logo" alt="un-logo">
<a class="navbar-brand" href="#">
</a>

</div>
</nav>
</footer>
</body>

</html>