<?php
session_start();
if(!$_SESSION['pseudo']) {
    header('Location: Connexion.php');
}
?>
<!DOCTYPE HTML>
<html>
<head>

</head>
<body>
<h3>RADIO TITAN CONSISTE EN DES PLAGES DE DIFFUSION D'UNE HEURE.<br />
ELLES SONT CONSTITUÉES D'INTERVIEWS DE 5 À 15 MINUTES.<br />
ENTRECOUPÉES DE PAUSES MUSICALES FAITES À PARTIR DES OEUVRES DE<br />
TITAN ET D'AUTRES ARTISTES.<br />
RADIO TITAN VISE À TOUCHER TOUT TYPE DE PUBLIC ET LA PARTICIPATION DE<br />
PERSONNES DE 12 À 60 ANS, AFIN D'ÉCHANGER SUR DIFFÉRENT SUJET TEL<br />
QUE ASTRONOMIE, CULINAIRE, AUTOMOBILE, SPORT, AGRICULTURE, HUMOUR,<br />
MUSIQUE, DOMOTIQUE, HANDICAP ET ACCESSIBILITÉ<br />
LES ENTRETIENT PODCASTS SE TIENDRONT EN PLUSIEURS LIEUX ET<br />
PLUSIEURS FORMES, LES LIEUX SERONT DIFFÉRENTS STUDIOS<br />
D'ENREGISTREMENTS EN PARTENARIAT AVEC RADIO TITAN, TOUT COMME LES<br />
MANIFESTATIONS ET MICRO-TROTTOIRS.<br />
DANS LE FUTUR, TRISTAN COMPTE BIEN FAIRE CONNAÎTRE À TRAVERS SES<br />
PODCAST, D'AUTRE ARTISTE(MUSIQUE, THÉÂTRE, DIVERS...). CONSEILLER ET<br />
ACCOMPAGNER LA MISE EN PLACE DE REPRÉSENTATION ARTISTIQUE AINSI<br />
AINSI QUE PROMOUVOIR ET SOUTENIR D'AUTRE ARTISTE DE TOUT HORIZON ET TOUT<br />
CELA TOUJOURS DANS LE MÊME OBJECTIF QUI EST «BRISER LES DIFFÉRENCES» </h3>
</body>
</html>